var magicstring2 = `
{
    "enchant_cost":{
        "book":{
            "0":1,
            "1":1,
            "2":1,
            "3":2,
            "4":1,
            "5":4,
            "6":2,
            "7":2,
            "8":2,
            "9":1,
            "10":1,
            "11":1,
            "12":1,
            "13":2,
            "14":2,
            "15":1,
            "16":4,
            "17":1,
            "18":2,
            "19":1,
            "20":2,
            "21":2,
            "22":4,
            "23":2,
            "24":2,
            "25":2,
            "26":2,
            "27":4,
            "28":4,
            "29":2,
            "30":2,
            "31":1,
            "32":4,
            "33":2,
            "34":1,
            "35":1,
            "36":4,
            "37":4,
            "38":2,
            "39":1,
            "40":2,
            "1000":2
        },
        "item":{
            "0":1,
            "1":2,
            "2":2,
            "3":4,
            "4":2,
            "5":8,
            "6":4,
            "7":4,
            "8":4,
            "9":1,
            "10":2,
            "11":2,
            "12":2,
            "13":4,
            "14":4,
            "15":1,
            "16":8,
            "17":2,
            "18":4,
            "19":1,
            "20":4,
            "21":4,
            "22":8,
            "23":4,
            "24":4,
            "25":4,
            "26":4,
            "27":8,
            "28":8,
            "29":4,
            "30":4,
            "31":1,
            "32":8,
            "33":4,
            "34":1,
            "35":2,
            "36":8,
            "37":8,
            "38":4,
            "39":2,
            "40":4,
            "1000":4
        }
    },
    "max_lv":{
        "0":4,
        "1":4,
        "2":4,
        "3":4,
        "4":4,
        "5":3,
        "6":3,
        "7":3,
        "8":1,
        "9":5,
        "10":5,
        "11":5,
        "12":2,
        "13":2,
        "14":3,
        "15":5,
        "16":1,
        "17":3,
        "18":3,
        "19":5,
        "20":2,
        "21":1,
        "22":1,
        "23":3,
        "24":3,
        "25":2,
        "26":1,
        "27":1,
        "28":1,
        "29":5,
        "30":3,
        "31":3,
        "32":1,
        "33":1,
        "34":4,
        "35":3,
        "36":3,
        "37":3,
        "38":4,
        "39":5,
        "40":3,
        "1000":3
    },
    "raw":[
        [
            0,
            "protection",
            "iv",
            1,
            1
        ],
        [
            1,
            "fire_protection",
            "iv",
            2,
            1
        ],
        [
            2,
            "feather_falling",
            "iv",
            2,
            1
        ],
        [
            3,
            "blast_protection",
            "iv",
            4,
            2
        ],
        [
            4,
            "projectile_protection",
            "iv",
            2,
            1
        ],
        [
            5,
            "thorns",
            "iii",
            8,
            4
        ],
        [
            6,
            "respiration",
            "iii",
            4,
            2
        ],
        [
            7,
            "depth_strider",
            "iii",
            4,
            2
        ],
        [
            8,
            "aqua_affinity",
            "i",
            4,
            2
        ],
        [
            9,
            "sharpness",
            "v",
            1,
            1
        ],
        [
            10,
            "smite",
            "v",
            2,
            1
        ],
        [
            11,
            "bane_of_arthropods",
            "v",
            2,
            1
        ],
        [
            12,
            "knockback",
            "ii",
            2,
            1
        ],
        [
            13,
            "fire_aspect",
            "ii",
            4,
            2
        ],
        [
            14,
            "looting",
            "iii",
            4,
            2
        ],
        [
            15,
            "efficiency",
            "v",
            1,
            1
        ],
        [
            16,
            "silk_touch",
            "i",
            8,
            4
        ],
        [
            17,
            "unbreaking",
            "iii",
            2,
            1
        ],
        [
            18,
            "fortune",
            "iii",
            4,
            2
        ],
        [
            19,
            "power",
            "v",
            1,
            1
        ],
        [
            20,
            "punch",
            "ii",
            4,
            2
        ],
        [
            21,
            "flame",
            "i",
            4,
            2
        ],
        [
            22,
            "infinity",
            "i",
            8,
            4
        ],
        [
            23,
            "luck_of_the_sea",
            "iii",
            4,
            2
        ],
        [
            24,
            "lure",
            "iii",
            4,
            2
        ],
        [
            25,
            "frost_walker",
            "ii",
            4,
            2
        ],
        [
            26,
            "mending",
            "i",
            4,
            2
        ],
        [
            27,
            "curse_of_binding",
            "i",
            8,
            4
        ],
        [
            28,
            "curse_of_vanishing",
            "i",
            8,
            4
        ],
        [
            29,
            "impaling",
            "v",
            4,
            2
        ],
        [
            30,
            "riptide",
            "iii",
            4,
            2
        ],
        [
            31,
            "loyalty",
            "iii",
            1,
            1
        ],
        [
            32,
            "channeling",
            "i",
            8,
            4
        ],
        [
            33,
            "multishot",
            "i",
            4,
            2
        ],
        [
            34,
            "piercing",
            "iv",
            1,
            1
        ],
        [
            35,
            "quick_charge",
            "iii",
            2,
            1
        ],
        [
            36,
            "soul_speed",
            "iii",
            8,
            4
        ],
        [
            37,
            "swift_sneak",
            "iii",
            8,
            4
        ],
        [
            38,
            "breach",
            "iv",
            4,
            2
        ],
        [
            39,
            "density",
            "v",
            2,
            1
        ],
        [
            40,
            "wind_burst",
            "iii",
            4,
            2
        ],
        [
            1000,
            "sweeping_edge",
            "iii",
            4,
            2
        ]
    ],
    "conflicts":{
        "0":[
            1,
            3,
            4
        ],
        "1":[
            0,
            3,
            4
        ],
        "3":[
            0,
            1,
            4
        ],
        "4":[
            0,
            1,
            3
        ],
        "7":[
            25
        ],
        "9":[
            10,
            11
        ],
        "10":[
            9,
            11,
            38,
            39
        ],
        "11":[
            9,
            10,
            38,
            39
        ],
        "16":[
            18
        ],
        "18":[
            16
        ],
        "22":[
            26
        ],
        "25":[
            7
        ],
        "26":[
            22
        ],
        "30":[
            31,
            32
        ],
        "31":[
            30
        ],
        "32":[
            30
        ],
        "33":[
            34
        ],
        "34":[
            33
        ],
        "38":[
            10,
            11,
            39
        ],
        "39":[
            10,
            11,
            38
        ]
    },
    "idmap":{
        "0":"protection",
        "1":"fire_protection",
        "2":"feather_falling",
        "3":"blast_protection",
        "4":"projectile_protection",
        "5":"thorns",
        "6":"respiration",
        "7":"depth_strider",
        "8":"aqua_affinity",
        "9":"sharpness",
        "10":"smite",
        "11":"bane_of_arthropods",
        "12":"knockback",
        "13":"fire_aspect",
        "14":"looting",
        "15":"efficiency",
        "16":"silk_touch",
        "17":"unbreaking",
        "18":"fortune",
        "19":"power",
        "20":"punch",
        "21":"flame",
        "22":"infinity",
        "23":"luck_of_the_sea",
        "24":"lure",
        "25":"frost_walker",
        "26":"mending",
        "27":"curse_of_binding",
        "28":"curse_of_vanishing",
        "29":"impaling",
        "30":"riptide",
        "31":"loyalty",
        "32":"channeling",
        "33":"multishot",
        "34":"piercing",
        "35":"quick_charge",
        "36":"soul_speed",
        "37":"swift_sneak",
        "38":"breach",
        "39":"density",
        "40":"wind_burst",
        "1000":"sweeping_edge",
        "protection":0,
        "fire_protection":1,
        "feather_falling":2,
        "blast_protection":3,
        "projectile_protection":4,
        "thorns":5,
        "respiration":6,
        "depth_strider":7,
        "aqua_affinity":8,
        "sharpness":9,
        "smite":10,
        "bane_of_arthropods":11,
        "knockback":12,
        "fire_aspect":13,
        "looting":14,
        "efficiency":15,
        "silk_touch":16,
        "unbreaking":17,
        "fortune":18,
        "power":19,
        "punch":20,
        "flame":21,
        "infinity":22,
        "luck_of_the_sea":23,
        "lure":24,
        "frost_walker":25,
        "mending":26,
        "curse_of_binding":27,
        "curse_of_vanishing":28,
        "impaling":29,
        "riptide":30,
        "loyalty":31,
        "channeling":32,
        "multishot":33,
        "piercing":34,
        "quick_charge":35,
        "soul_speed":36,
        "swift_sneak":37,
        "sweeping_edge":1000,
        "breach":"38",
        "density":"39",
        "wind_burst":"40"
    },
    "enchantable":{
        "0":[
            "helmet",
            "chestplate",
            "leggings",
            "boots",
            "turtle_shell"
        ],
        "1":[
            "helmet",
            "chestplate",
            "leggings",
            "boots",
            "turtle_shell"
        ],
        "2":[
            "boots"
        ],
        "3":[
            "helmet",
            "chestplate",
            "leggings",
            "boots",
            "turtle_shell"
        ],
        "4":[
            "helmet",
            "chestplate",
            "leggings",
            "boots",
            "turtle_shell"
        ],
        "5":[
            "helmet",
            "chestplate",
            "leggings",
            "boots",
            "turtle_shell"
        ],
        "6":[
            "helmet",
            "turtle_shell"
        ],
        "7":[
            "boots"
        ],
        "8":[
            "helmet",
            "turtle_shell"
        ],
        "9":[
            "sword",
            "axe"
        ],
        "10":[
            "sword",
            "axe",
            "mace"
        ],
        "11":[
            "sword",
            "axe",
            "mace"
        ],
        "12":[
            "sword"
        ],
        "13":[
            "sword",
            "mace"
        ],
        "14":[
            "sword"
        ],
        "15":[
            "pickaxe",
            "shovel",
            "axe",
            "hoe",
            "shears"
        ],
        "16":[
            "pickaxe",
            "shovel",
            "axe",
            "hoe"
        ],
        "17":[
            "helmet",
            "chestplate",
            "leggings",
            "boots",
            "pickaxe",
            "shovel",
            "axe",
            "sword",
            "hoe",
            "fishing_rod",
            "bow",
            "shears",
            "flint_and_steel",
            "carrot_on_a_stick",
            "warped_fungus_on_a_stick",
            "shield",
            "elytra",
            "trident",
            "turtle_shell",
            "crossbow",
            "mace"
        ],
        "18":[
            "pickaxe",
            "shovel",
            "axe",
            "hoe"
        ],
        "19":[
            "bow"
        ],
        "20":[
            "bow"
        ],
        "21":[
            "bow"
        ],
        "22":[
            "bow"
        ],
        "23":[
            "fishing_rod"
        ],
        "24":[
            "fishing_rod"
        ],
        "25":[
            "boots"
        ],
        "26":[
            "helmet",
            "chestplate",
            "leggings",
            "boots",
            "pickaxe",
            "shovel",
            "axe",
            "sword",
            "hoe",
            "fishing_rod",
            "bow",
            "shears",
            "flint_and_steel",
            "carrot_on_a_stick",
            "warped_fungus_on_a_stick",
            "shield",
            "elytra",
            "trident",
            "turtle_shell",
            "crossbow",
            "mace"
        ],
        "27":[
            "helmet",
            "chestplate",
            "leggings",
            "boots",
            "elytra",
            "turtle_shell"
        ],
        "28":[
            "helmet",
            "chestplate",
            "leggings",
            "boots",
            "pickaxe",
            "shovel",
            "axe",
            "sword",
            "hoe",
            "fishing_rod",
            "bow",
            "shears",
            "flint_and_steel",
            "carrot_on_a_stick",
            "warped_fungus_on_a_stick",
            "shield",
            "elytra",
            "helmet",
            "trident",
            "turtle_shell",
            "crossbow",
            "mace"
        ],
        "29":[
            "trident"
        ],
        "30":[
            "trident"
        ],
        "31":[
            "trident"
        ],
        "32":[
            "trident"
        ],
        "33":[
            "crossbow"
        ],
        "34":[
            "crossbow"
        ],
        "35":[
            "crossbow"
        ],
        "36":[
            "boots"
        ],
        "37":[
            "leggings"
        ],
        "38":[
            "mace"
        ],
        "39":[
            "mace"
        ],
        "40":[
            "mace"
        ],
        "1000":[
            "sword"
        ]
    },
    "enchantbytool":{
        "helmet":[
            "0",
            "1",
            "3",
            "4",
            "5",
            "6",
            "8",
            "17",
            "26",
            "27",
            "28"
        ],
        "chestplate":[
            "0",
            "1",
            "3",
            "4",
            "5",
            "17",
            "26",
            "27",
            "28"
        ],
        "leggings":[
            "0",
            "1",
            "3",
            "4",
            "5",
            "17",
            "26",
            "27",
            "28",
            "37"
        ],
        "boots":[
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "7",
            "17",
            "25",
            "26",
            "27",
            "28",
            "36"
        ],
        "turtle_shell":[
            "0",
            "1",
            "3",
            "4",
            "5",
            "6",
            "8",
            "17",
            "26",
            "27",
            "28"
        ],
        "sword":[
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "17",
            "26",
            "28",
            "1000"
        ],
        "axe":[
            "9",
            "10",
            "11",
            "15",
            "16",
            "17",
            "18",
            "26",
            "28"
        ],
        "pickaxe":[
            "15",
            "16",
            "17",
            "18",
            "26",
            "28"
        ],
        "shovel":[
            "15",
            "16",
            "17",
            "18",
            "26",
            "28"
        ],
        "hoe":[
            "15",
            "16",
            "17",
            "18",
            "26",
            "28"
        ],
        "shears":[
            "15",
            "17",
            "26",
            "28"
        ],
        "fishing_rod":[
            "17",
            "23",
            "24",
            "26",
            "28"
        ],
        "bow":[
            "17",
            "19",
            "20",
            "21",
            "22",
            "26",
            "28"
        ],
        "flint_and_steel":[
            "17",
            "26",
            "28"
        ],
        "carrot_on_a_stick":[
            "17",
            "26",
            "28"
        ],
        "warped_fungus_on_a_stick":[
            "17",
            "26",
            "28"
        ],
        "shield":[
            "17",
            "26",
            "28"
        ],
        "elytra":[
            "17",
            "26",
            "27",
            "28"
        ],
        "trident":[
            "17",
            "26",
            "28",
            "29",
            "30",
            "31",
            "32"
        ],
        "crossbow":[
            "17",
            "26",
            "28",
            "33",
            "34",
            "35"
        ],
        "mace":[
            "10",
            "11",
            "13",
            "17",
            "26",
            "28",
            "38",
            "39",
            "40"
        ],
        "enchanted_book":[
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "28",
            "29",
            "30",
            "31",
            "32",
            "33",
            "34",
            "35",
            "36",
            "37",
            "38",
            "39",
            "40",
            "1000"
        ]
    }
}
`
